custom:
  environment: ${ENVIRONMENT:cloud}
  version: ${VERSION:unavailable}
  classification: ${CLASSIFICATION:UNCLASS}
  caveat: ${CAVEAT:IL2}
  mattermosttoken: testToken
  mattermosturl: http://mattermost.foo
  localKeycloakUid: keycloak-sub-123
  jwtAdminGroup: ${ADMIN_GROUP:midas-IL2-admin}
  gitLabUrl: ${GITLAB_API_URL:NONE}
  gitLabAccessToken: ${GITLAB_ACCESS_TOKEN:NONE}
  randomString: ${RANDOM_STRING:NONE}

server:
  port: 8000

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    # org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false

        jdbc:
          time_zone: "UTC"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_ADMIN_USER}
    password: ${MYSQL_DB_ADMIN_PASSWORD}

  flyway:
    failed-last-migration: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 6KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  api-docs:
    path: /rest/docs

mattermost:
  token: ${MATTERMOST_TOKEN:#{null}}
  url: ${MATTERMOST_URL:#{null}}

