custom:
  environment: ${ENVIRONMENT:cloud}
  version: ${VERSION:unavailable}
  classification: ${CLASSIFICATION:UNCLASS}
  caveat: ${CAVEAT:IL2}
  mattermosttoken: testToken
  mattermosturl: http://mattermost.foo
  localKeycloakUid: keycloak-sub-123
  jwtAdminGroup: ${ADMIN_GROUP:midas-IL2-admin}
  gitLabUrl: ${GITLAB_API_URL:NONE}
  gitLabAccessToken: ${GITLAB_ACCESS_TOKEN:NONE}
  key: ${KEY:${MYSQL_DB_ADMIN_PASSWORD}}
  salt: ${SALT:${MYSQL_HOST}}
  allowedOrigin: ${ALLOWED_ORIGIN:*dso.mil}
  dbName: ${MYSQL_DB_NAME}

s3:
  minioAccessKey: ${MINIO_ACCESS_KEY}
  minioSecretKey: ${MINIO_SECRET_KEY}
  minioHost: ${MINIO_HOST}
  minioBucketName: ${MINIO_BUCKET_NAME}
  awsDefaultRegion: ${AWS_DEFAULT_REGION}


server:
  port: 8000

logging:
  level:
    org:
      springframework:
        security: WARN
        web: WARN
    root: INFO

spring:
  main:
    allow-circular-references: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false

        jdbc:
          time_zone: "UTC"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_ADMIN_USER}
    password: ${MYSQL_DB_ADMIN_PASSWORD}

  flyway:
    failed-last-migration: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 6KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  api-docs:
    path: /rest/docs

mattermost:
  token: ${MATTERMOST_TOKEN:#{null}}
  url: ${MATTERMOST_URL:#{null}}

