version: '3.7'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: unless-stopped
    container_name: app-db
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=password

  sso:
    image: jboss/keycloak:10.0.2
    restart: always
    ports:
      - 10000:8080
    volumes:
      - ./keycloak/p1.json:/tmp/p1.json
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/p1.json
      - DB_VENDOR=h2

  adminer:
    image: adminer
    restart: always
    container_name: app-db-adminer
    ports:
      - 8181:8080


  minio:
    container_name: minio
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_REGION_NAME: us-gov-west-1
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio123 minio123;
      /usr/bin/mc mb -p myminio/midas;
      exit 0;
      "

volumes:
  minio_data: