-- Set default char set, settings supports emoji unicode
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
ALTER DATABASE appDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Create table for autogenerated hibernate IDs
CREATE TABLE `hibernate_sequence` (`next_val` BIGINT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `hibernate_sequence` (next_val) VALUES(2);

-- store basic P1 user info
CREATE TABLE `users` (
  `id` BIGINT NOT NULL,
  `dod_id` BIGINT,
  `keycloak_uid` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `display_name` VARCHAR(100),
  `roles` BIGINT NOT NULL DEFAULT 0,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_disabled` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- add a user for local development, user is disabled in production
INSERT INTO `users` (id, dod_id, keycloak_uid, username, roles)
  VALUES(1, 9999999999, 'keycloak-sub-123', 'localuser', 1);
